### ISSUE TITLE
Graafikute plokk proovipunkti vaates

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#14]
Proovipunkti detailvaates tahaks kasutaja näha proovide andmeid nii numbriliselt (sarnasel kujul nagu proovi otsingus) kui graafikutel. Analüüside numbrid oleks mõistlik panna proovide tabelisse, kuigi see läheb laiaks. Graafikute ploki, kus kuvatakse kõigi valitud parameetrite muutusi läbilõikes, võiks aga teha eraldi allapoole, pealkiri Analüütilised andmed. Selle ploki alguses võiks olla sama veergude valiku widget nagu proovide otsingus. Valida saaks kuni 10 parameetrit, vaikimisi oleks valitud ja kuvatud looduslik niiskus, lagunemisaste, tuhasus.

**Comment by ollehints** [comment]
graafiku-joonistamise programme on mitmeid, nt: https://apexcharts.com/vue-chart-demos/scatter-charts/basic
aga, tulevikku silmas pidades, võiks vaadata ka midagi sellist: https://github.com/JustinGOSSES/wellioviz

**Comment by ollehints** [comment]
praegu näitab seda plokki proovi vaates (https://turvas.geoloogia.info/#/sample/145684), aga peaks olema ikka proovipunkti all (https://turvas.geoloogia.info/#/site/5781) ja näitama kõiki vastava uuringupunkti proovide andmeid.

**Comment by enmust** [comment]
Esialgne graafik lisatud, et praegu võtsin kasutusse chart.js library.

**Comment by ollehints** [comment]
iga parameetri kohta peaks tulema eraldi graafik fikseeritud laiusega (kuna väärtuste skaalad võivad olla väga erinevad). Sel juhul pole vaja erinevaid markereid.
markerite suurus peaks olema konstantne, kuna x telg näitab väärust niigi. Suurus kordab sama ja teeb pildi kirjuks (markeri suurust on mõtet muuta ainult kaardil, ja sealgi juhul kui samas geograafilises punktis pole mitut andmepunkti).

**Comment by ollehints** [comment]
graafik peaks värskenema kui nt valida kaardilt teine proovipunkt.

**Comment by ollehints** [comment]
Graafiku vertikaalne skaala peaks olema sama erinevate proovipunktide puhul. St graafiku kõrgus sõltub uuringupunkti sügavusest (site.depth; kui seda pole, siis mingi vaikimisi suurus). Sel juhul oleks võimalik sama ala eri punkte operatiivselt ja objektiivselt võrrelda.

**Comment by ollehints** [comment]
- iga parameeter peaks olema eraldi graafiku objekt koos telgede jms-ga, laius 300px
- kui graafiku kõrgust pole chart.js-iga mugav staatiliseks sättida siis võib jääda ka nii nagu on
- praegu on nii, et ala kaardil järjest punkte valida siis muutub graafiku info ajalise nihkega, näidates eelmise proovipunkti infot (mis ei lähe kokku proovide tabeli sügavustega):
![image](https://user-images.githubusercontent.com/14974887/76466004-733e0780-63ef-11ea-953b-49e1733f1cb0.png)

**Comment by ollehints** [comment]
graafiku joonistamisel oleks õigem võtta y-telje väärtusteks mitte depth vaid (depth+depth_interval)/2

**Comment by ollehints** [comment]
praegusel kujul animatsioon on pigem häiriv, kui jätta, siis mingi fade in variant, või siis katsetada punktide liikumist vasakult paremale.

**Comment by enmust** [comment]
> kui graafiku kõrgust pole chart.js-iga mugav staatiliseks sättida siis võib jääda ka nii nagu on

Graafikule saab fikseeritud kõrguse ja laiuse anda, siis ta ei oleks enam responsive. Pigem oleks mõistlikum panna min-height ja min-width väärtused.

> iga parameetri kohta peaks tulema eraldi graafik fikseeritud laiusega (kuna väärtuste skaalad võivad olla väga erinevad). Sel juhul pole vaja erinevaid markereid.

Kas ma saan õigesti aru, et siis peaks iga valiku puhul (max 10 hetkel) tulema graafik?

Saaks ka midagi siukest teha:
![image](https://user-images.githubusercontent.com/14908993/76510315-14fa3e80-645a-11ea-82d7-cd34f3bbfa4a.png)

> Graafiku vertikaalne skaala peaks olema sama erinevate proovipunktide puhul. St graafiku kõrgus sõltub uuringupunkti sügavusest (site.depth; kui seda pole, siis mingi vaikimisi suurus)

By default on pm fit to screen, aga saaks anda ise min ja max väärtused y-teljele.

> iga parameeter peaks olema eraldi graafiku objekt koos telgede jms-ga, laius 300px

Et siis oleks eraldi graafik fikseeritud laiusega 300px?

**Comment by ollehints** [comment]
Ühele graafikule saab vahel asju kokku panna küll, eriti kui on tegemist sama analüüsi tulemustega. Aga alati pole see loogiline ega ülevaatlik (nt pH ja mingi takson ei ole loogiliselt samal graafikul, mõnel juhul on aga skaalad väga erinevad).
Seetõttu on üldjuhul lihtsam ja kindlam variant panna iga parameeter omaette graafikule. Kõrgus võiks vist jääda varieeruv, aga laius fikseerida (kui mitu graafikut ei mahu ära, siis  voolab järgmisele reale.

![image](https://user-images.githubusercontent.com/14974887/76512383-3ad51280-645d-11ea-9524-31a3eb2c2419.png)

**Comment by ollehints** [comment]
joonega tekib probleem kui proovid pole sisestatud järjest: https://turvas.geoloogia.info/#/site/8514
st peaks enne sorteerima sügavuse järgi. 
sama probleem ka proovide tabelis (proovipunkti vaates) kus vaikimis sorteering ID järgi, peaks vist seal ka sügavuse järgi sortima.
