### ISSUE TITLE
ala piirid geoserverist

### ISSUE THREAD

**Issue by enmust** [geocollections/turvas#18]
Praegune request: http://gis.geocollections.info/geoserver/turvas/ows?service=WFS&version=1.0.0&request=GetFeature&maxFeatures=50&outputFormat=application%2Fjson&typeName=turvas%3ATurbaalad&CQL_FILTER=area_id%3D223

leaflet tahab koordinaate saada lat lng formaadis, tuleb uurida formattimise jms võimalusi

**Comment by ollehints** [comment]
ala piirid on sageli liiga suured, põhiliselt oleks vaja ainult bounding boxi, et alale suumida kui area_id on teada. aga seda ei saa vist wms/wfs-iga kätte. variant küsida postgisilt - aga selleks jälle vaja api funktsionaalsust laiendada (või eraldi miniatuurne API mis asendaks ka WMS getfeatureinfo päringu).

**Comment by ollehints** [comment]
piirid saab kätte, aga osa neist on päris mahukad, võib testida ka kuvamine ala, mitte punktide, bounding boxi extenti järgi oleks ok.
