### ISSUE TITLE
Kaardivaate küsimused

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#2]
- Kaardi algvaade võiks olla fotokaart, kuna tumedal taustal paistavad alad ja punktid paremini välja, samuti on väiksem probleem kirjade fondi udususega. 
- Alade ja uuringupunktide kihid võiks olla avavaates aktiveeritud, ka maakonnapiir.
- Kõik proovipunktid saab nüüd kätte wmsist: 'LAYERS': 'turvas:Turbapunktid'
- Kõige ülemine kiht kaardil on uuringupunktid, selle all turbaalad, siis maardlad, soosetted, turbaalade plaanid ja siis ülejäänud. Aluskaardid võiks ka legendis olla kõige all. Reljeef on samuti aluskaart. seda peaks saama kasutada ka ilma fotokaardi/põhikaardita.

**Comment by ollehints** [comment]
Konkreetseid turbaalasid saab küsida wfs CQL päringuga, xml või json vormingus, nt:
http://gis.geocollections.info/geoserver/turvas/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=turvas%3ATurbaalad&CQL_FILTER=area_id=544&outputFormat=application/json 
Sama CQL ka wmsi puhul: http://gis.geocollections.info/geoserver/turvas/wms?service=WMS&version=1.1.0&request=GetMap&layers=turvas%3ATurbaalad&bbox=382312.34375%2C6376397.0%2C722794.8125%2C6607497.5&width=768&height=521&srs=EPSG%3A3301&format=application/openlayers&&CQL_FILTER=area_id=544

**Comment by ollehints** [comment]
Ühe turbaala punktide päring: http://gis.geocollections.info/geoserver/turvas/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=turvas%3ATurbapunktid&CQL_FILTER=area_id=544&outputFormat=application/json

**Comment by enmust** [comment]
Leafleti vaikimisi kihitide vidinaga väga midagi teha ei saa, lisafunktsionaalsuse jaoks tuleks kasutada mõnda community tehtud vidinat. 
See jättis praegu kõige parema mulje https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree
Teised on leitavad siit: https://leafletjs.com/plugins.html#layer-switching-controls
