### ISSUE TITLE
kursor kaardil

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#21]
Juhul kui kaardil on võimalik punkte/alasid valida võiks kursor olla pigem rist (crosshair) kui käsi.
Peab proovima kas zoom ja drag tunduks sel juhul kasutajale loomupärane või mitte. 
Variant oleks pakkuda kasutajale eraldi tööriistakasti: drag, zoom, select, measure jne - sel juhul muutuks kursor vastavalt valitud funktsioonile (seda võib kaaluda, kui muud funktsioonid olemas).

**Comment by enmust** [comment]
Ma arvan, et see ei oleks kasutajasõbralik, kui praegust drag või zoom funktsionaalsust saaks/peaks piirama kasutades eraldi n-ö tööriistakasti. + select, measure jms leafleti pluginad tulevad nagunii oma control buttoniga
