### ISSUE TITLE
Botaanilise koostise graafik

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#22]
Kuivõrd chart.js on juba seotud, siis oleks lihtne proovi detailinfo vaates botaanilise koostise all joonistada välja ringdiagramm või barankadiagramm (doughnut) parameetritest (parameter_name), millel numbriline protsent olemas.
Perspektiivis on võibolla vajalik defineerida mingid summaarsed parameetrid, mis on kõnekamad kui konkreetsed taksonid, nt panna kokku kõik Sphagnum* taksonid koondparameetri "Turbasamblad" alla, samuti summeerida kõik üksikud puuliigid (Picea, Pinus, Salix jne) ja määratlemata puud (Lignum) koondmuutuja "Puud" alla. Kas ja kuidas seda teha, peab uurima spetsialistidelt.

**Comment by enmust** [comment]
Grupeerimine tundub hea mõte, võibolla kui vaja saaks ju luua mingeid graafikuid kogu andmestiku peale või siis maakonniti jms.
