### ISSUE TITLE
Otsing eestikeelse taimenime järgi

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#23]
Kas proovide otsingus saaks lihtsalt lisada botaanika parameetrite juurde ka eestikeelse nime (seal kus seotud eestikeelne nimi olemas), nt:
- praegu: "Carex lasiocarpa | Clas"
- võiks olla: "Carex lasiocarpa | Clas (niitjas tarn)"

**Comment by enmust** [comment]
Praegu kergelt kohe ei saa, tuleb uurida seda facet asja, äkki saab seal kuidagi kombineerida vms

**Comment by ollehints** [comment]
vajadusel saab teha mingi eraldi indeksi nimedele
