### ISSUE TITLE
Proovi detailvaate alternatiivne lahendus

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#24]
Tekkis selline uitmõte, et proovi vaates on kaardist suhteliselt vähe kasu, kuid võibolla tahaks kasutaja näha korraga proovipunkti infot ja proovide infot:
![Capture2](https://user-images.githubusercontent.com/14974887/76613152-3fb1c900-6526-11ea-9886-6e78fbdaaa9b.PNG)
Peab arutama spetsialistidega.

**Comment by enmust** [comment]
Ma natuke testisin, ja see peaks tehtav olema küll, aga nõuab mõningate asjade ümber tegemist. + kui see peaks käiku minema, tuleks loogika ka üle arutada, et mis by default lahti on, mis siis kui proove pole vms. 

Alternatiivina saaks saaks lahendada selle nii, et site detailvaates proovi peale vajutades avaneb hoopis uus aken ja siis kui proove klikkida avatakse uus proov kogu aeg selle avatud akna sees
