### ISSUE TITLE
Kaardi legend

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#25]
Kaardil peaks olema legend põhiliste tingmärkide kohta (eriti need mis avalehel näha - alad ja punktid).

**Comment by enmust** [comment]
Kas seda võiks täiustada näiteks aluspõhja geoloogia 400k kihi vms kihi puhul?

**Comment by ollehints** [comment]
Aluspõhja geoloogia kiht pole turba jaoks kuigi oluline ja värvide legend on seal pikk. Pigem piirduda esialgu turbaalade ja -punktidega.
