### ISSUE TITLE
kas loobuda urlis #-st

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#28]
kas urlis trellidest loobumine annaks mingi negatiivse efekti?

**Comment by enmust** [comment]
Pigem loobuda, aga selleks tuleb server confida nii, et redirectiks index.html. Ma praegu eemaldasin juba #. 
Siin on mingid confi näited ka: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by ollehints** [comment]
Apache'i conf muudetud, kui järjest brausida, siis toimib, aga kui viidata otse a la  https://turvas.geoloogia.info/sample/145947 siis näitab file not found

**Comment by enmust** [comment]
ma proovisin ka juba confi muuta, aga oli sama probleem. Samas editis see töötab, tuleb uurida

**Comment by enmust** [comment]
Korras
