### ISSUE TITLE
Proovide otsing analüüsitulemuste järgi

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#3]
Solr-is on nüüd olemas eraldi indeksid peat_analysis ja peat_samples. Viimane on risttabel, kust saab teha proovide/analüüsipunktide otsingut analüüsitulemuste järgi, nt: 
.../peat_samples/select?fq=pH%3A%5B*%20TO%204%5D&fq=rock%3Amadalsooturvas&fq=tuhasus%3A%5B5%20TO%206%5D&q=*%3A*
Küsimus - kuidas lahendada ühendus rakenduse ja solri vahel - kas läbi api või node-i?

**Comment by enmust** [comment]
endale infoks: fq=pH:[* TO 4]&fq=rock:madalsooturvas&fq=tuhasus:[5 TO 6]&q=:

Praegu on lahendatud läbi api, kui api kaudu probleeme ei teki, siis ma pigem jätaks nii nagu on.

**Comment by ollehints** [comment]
api conf täiendatud, otsing toimib kujul:
https://api.geocollections.info/solr/peat_samples/?fq=pH:[*%20TO%204]&fq=rock:madalsooturvas&fq=tuhasus:[5%20TO%206]&q=*
