### ISSUE TITLE
Projekti info leht

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#30]
Projekti info taustapiltideks võiks kasutada rabade ortofotosid, valikud kataloogis 3D.
Tutvustav tekst, seniks kuni lõplik versioon pole valmis, võiks olla järgmine (kõik mahub ühele lehele):

> Keskkonnainvesteeringute Keskuse projektide nr 12623 "Turbaalaste uurimistulemuste digitaliseerimine ja andmebaasi koostamine I etapp (Harju, Rapla, Pärnu maakond)" ja 14460 "Turbaalaste uurimistulemuste digitaliseerimine ja andmebaasi koostamine II etapp" eesmärgiks oli turba uurimisel kogutud andmestiku koondamine, digiteerimine ning erinevatele sihtrühmadele 
> (turbatootjad, ametnikud, keskkonnaspetsialistid, üliõpilased, loodusehuvilised) kättesaadavaks tegemine.
> Turbageoloogiline originaalandmestik on kogutud Eesti Geoloogiakeskuse poolt ning seda säilitatakse Geoloogiafondis. Andmete digiteerimise ja andembaasi koostamise viis läbi Tallinna Tehnikaülikooli geoloogia instituut 2016-2020.

**Comment by ollehints** [comment]
siia peaks lisama ka KIKi logo samal kujul nagu avalehel.
samal ajal /area, /site ja /sample vaadetes pole KIKi logo kuvamine vajalik (praegu ka veidi eksitav kuna viitab nagu oleks kaart KIKiga seotud, tegelikult on kogu projekt ja portaal KIKi toel valminud).
alternatiiv - mõelda footerile, kus saaks kuvada rahastaja ja ka teostaja infot ja kontakte.

**Comment by enmust** [comment]
KIKiga seotud info saaks ka muidu sinna /about alla panna. 

> alternatiiv - mõelda footerile, kus saaks kuvada rahastaja ja ka teostaja infot ja kontakte.

Lisasin tühja footeri, saab vaadata kuidas tundub jms.
