### ISSUE TITLE
failide allalaadimine

### ISSUE THREAD

**Issue by enmust** [geocollections/turvas#35]
Failid serverisse ja lingid vaja lisada.

**Comment by ollehints** [comment]
Allalaaditavate andmete järjekord, esimene link esialgu lehele https://doi.geocollections.info/10.15152/GEO.487:

**Allalaadimine**
- KIKi projekti nr 14460 seletuskiri ja kasutusjuhend (pdf vormingus, 1MB)
- Eesti turbauuringute andmebaas (põhiandmed xlsx vormingus, 7MB, registreeritud andmekogum DOI:10.15152/GEO.487).
- Turbaalade georefereeritud tehnilised plaanid (geotiff vormingus, ~6GB)
- Mahajäetud turbaväljade failid (lingid Geoloogiafondi aruannetele): 1. etapp, 2. etapp, 3. etapp, 4. etapp
