### ISSUE TITLE
taustapildid

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#44]
Sisulehtede taustapildid võiks vahelduda sujuva animatsiooniga ja/või aeglasemalt - muidu häirib pikema teksti lugemisel.
Piltide valiku osas peab veel mõtlema - võiks olla siiski ka turvast näha, rabataimestiku ja laugaste kõrval.

**Comment by enmust** [comment]
Hetkel roteeruvad pildid iga 6 sekundi tagant, et võiks võibolla veel mõned lisada
