### ISSUE TITLE
Proovide otsing

### ISSUE THREAD

**Issue by enmust** [geocollections/turvas#5]
| maakond | ala nimi | proovipunkti nimi | analüüsitulemuste järgi | parameetrite näitamine |

+ tabeli juures ka otsing nagu on ala ja proovipunkti juures.

**Comment by enmust** [comment]
depth ja depth_interval otsing peale proovipunkte

**Comment by ollehints** [comment]
![20200302_211803093_iOS](https://user-images.githubusercontent.com/14974887/75719462-72b1bc80-5cdd-11ea-8148-8a2914edd62d.png)

**Comment by enmust** [comment]
esmane versioon on live

**Comment by ollehints** [comment]
- Sügavuse otsing oleks vist siiski loogilisem lahendada alates - kuni otsinguga: (depth:[alates TO kuni] OR depth_interval:[alates TO kuni])
- parameetreid näitab praegu vähem kui neid kokku on, nt Sphagnum järgi ei leia midagi (see on turbasammal).
- eesmärk on siduda peamised taksonid taxon tabeliga, sealtkaudu saab kätte plutof_taxon_id (olemas peat_taxa indeksis), mis võimaldab linkida eElurikkusesse: https://elurikkus.ee/bie-hub/species/7368. Kas selline link võiks tekkida nt analüüsi otsingutulemuste päisesse? Kindlasti võiks see tulla proovi detailvaatesse bot koostise analüüsi alla, kus on määratud taksonite nimekiri.

**Comment by ollehints** [comment]
taksonite linkimine e-elurikkusesse: mõte oli selline, et kui kasutaja valib nt liigi Sphagnum fuscum, siis, juhul kui sellele vastav plutof_taxon_id on teada, siis kuvatakse taksoni nimi tabeli veeru päises lingina. Lihtsalt taksoni numbreid proovi real kuvada pole otstarbekas.

**Comment by ollehints** [comment]
ok, see oleks siiski keeruline kuna kattub sorteerimise funktsiooniga - jätame linkimise proovi/analüüsi detailvaatesse.
