### ISSUE TITLE
Detailvaate põhiinfo peitmine

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#8]
Detailvaadete (ala, proovipunkt, proov) põhiinfo peaks olema võimalik peita (accordion) nii, et ainult pealkiri jääb näha. See on kasulik nt kui proovipunktist on palju proove, mida tahaks korraga ekraanil näha. Sel juhul võiks olla ka proovide vaikimisi hulk tabelis 50 mitte 10 (valikud, 10, 50, 100).

**Comment by enmust** [comment]
Sulgen selle, kuna plokkide peitmine on viidud #11 ning vaikimisi kuvatavate proovide hulk ei ole enam piiratud.
