### ISSUE TITLE
Proovi detailinfo

### ISSUE THREAD

**Issue by ollehints** [geocollections/turvas#9]
![20200302_213700351_iOS](https://user-images.githubusercontent.com/14974887/75720343-fddf8200-5cde-11ea-9f98-16f2c93245f6.png)

**Comment by ollehints** [comment]
- proovi detailinfo tabelisse lisada:
  - maakond
  - depth
  - depth_interval
- pole vaja näidata: site_depth, egf, avamus, mis kuuluvad proovipunkti/ala vaate juurde.
- alapealkiri Taksonid asemele "Botaaniline koostis"
- botaanika tabelisse lisada väli value, päises "Osakaal (%)"
- päises Link asemel "e-Elurikkus", lahtri sisu puhul ikoonis suurus väiksemaks (et ei teeks rida kõrgemaks).
- botaanika tulemuste tabelisse lisada eestikeelne nimi, API päring a la:  
https://api.geocollections.info/taxon_common_name/?taxon__in=17435,17436,17437&language=4&fields=taxon,name
- Botaanika juures vajalik näidata määraja nime ja laborit (mitte dubleerida igal real)
- Analüüside tabeli võiks organiseerida nii, et poleks vaja korrata labori nime ja isikut. Juurde oleks vaja lisada analüüsi aeg ja persoonide nimi tekstina (agent_txt).
- mida teha ühikutega analüüsi tabelis? kuidagi oleks vaja kuvada.
- taksoni ladinakeelne nimi kursiivi

**Comment by ollehints** [comment]
Bot koostise info OK, kuna tegemist ühe analüüsiga. 
Analüüside ploki puhul võib aga igal analüüsil olla erinev labor , analüüsija, aeg jne. nt https://turvas.geoloogia.info/#/sample/145670 puhul on esimesed kaks meetodit/analüüsi EGK turbalaborist, kui mõlemal on erinevad persoonid (agent_free). Turba kasutusala hinnang on tehtud Orru poolt, aga mitte EGK turbalabori all/ajal. 
Kaks varianti -- kas teha eraldi tulemuste tabelid iga analüüsi kohta, või siis eemaldada analüüsi üldinfo, aga lisada analüüsi detailvaade. Esimene variant on lihtsam, teine on kasutuses geokogude portaalis: nt http://geocollections.info/sample/77518 ja http://geocollections.info/analysis/19004.

**Comment by enmust** [comment]
Oleks võimalik ka umbes nii teha
![image](https://user-images.githubusercontent.com/14908993/76090770-d3364780-5fc4-11ea-8461-89bf16dff858.png)

Või käskida tabelil ainult mobile view olla:
![image](https://user-images.githubusercontent.com/14908993/76091051-7f782e00-5fc5-11ea-8a4f-16bec182cc43.png)

Indeksisse oleks vaja kuupäeva ja persoonide välju.

**Comment by ollehints** [comment]
esimene variant ok, moblavaate võiks keelata - arvude tabeleid on seal tegelikult ebamugav jälgida - horizontal scroll ok.
peat_analysis ja peat_taxa indeksis nüüd olemas ka agent_analysed_free ja date_analysed_free.

**Comment by ollehints** [comment]
- lisaks olemas ka parameter_name_et, seega pole vaja eraldi päringut eestikeelsetele nimedele
- botaanilise koostise tabeli võiks sorteerida value DESC järgi, st kõige arvukam/olulisem komponent kõige üleval

**Comment by ollehints** [comment]
Proovi detailinfo juurde võiks lisada rock_name, stratigraphy, stratigraphy_free
